Select 
	
	U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD, C.CITY AS İL, T.TOWN AS ILÇE , D.DISTRICT AS SEMT,
	A.ADDRESSTEXT AS ACIKADDRESS, O.ID AS SİPARİŞID , O.DATE_ AS TARIH, O.TOTALPRICE AS TOPLAMTUTAR,
	P.DATE_ AS ODEMETARIHI, P.APPROVECODE AS BANKAONAYKODU, I.DATE_ AS FATURATARİHİ , I.CARGOFICHENO AS KARGOFİŞNO,
	ITM.ITEMCODE AS URUNKODU, ITM.ITEMNAME AS URUNADI , OD.AMOUNT AS MIKTAR, OD.UNITPRICE AS BRIMFIYAT,
	OD.LINETOTAL AS SATIRTOPLAMI

from ORDERS AS O

	INNER JOIN USERS AS U ON U.ID = O.USERID
	INNER JOIN ADDRESS AS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES AS C ON C.ID = A.CITYID
	INNER JOIN TOWNS AS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS AS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS AS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES AS I ON I.ORDERID = O.ID 
	INNER JOIN ORDERDETAILS AS OD ON OD.ORDERID = O.ID 
	INNER JOIN ITEMS AS ITM ON ITM.ID = OD.ITEMID

WHERE U.NAMESURNAME = 'm s'
--WHERE O.ID = 3314
